---
name: batch-holdings-update
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12,<3.13
  - python-dotenv>=1.0.1,<2
  - orjson>=3.11.1
  - pip
  - pip:
    - pyfolioclient>=0.1.7,<1
